server {
    listen 80;
    server_name groven.in *.groven.in;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.groven.in;

    ssl_certificate     /etc/letsencrypt/live/groven.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groven.in/privkey.pem;

    location /ws/ {
        proxy_pass http://daphne:8001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name groven.in *.groven.in;

    ssl_certificate     /etc/letsencrypt/live/groven.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groven.in/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}