# Generated by Django 6.0.5 on 2026-06-08 04:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0007_alter_client_membership"),
        ("request_management", "0005_file_s3_key"),
        ("tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("new_request", "New Request"),
                            ("status_change", "Status Change"),
                            ("new_message", "New Message"),
                            ("files_delivered", "Files Delivered"),
                            ("invite_accepted", "Invite Accepted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="clients.client",
                    ),
                ),
                (
                    "related_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="request_management.request",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant"], name="idx_notifications_tenant_id"),
                    models.Index(
                        fields=["recipient"], name="idx_notifications_recipient_id"
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="idx_notifications_recipient_unread",
                    ),
                    models.Index(
                        fields=["tenant", "recipient", "created_at"],
                        name="idx_notifications_feed",
                    ),
                    models.Index(
                        fields=["event_type"], name="idx_notifications_event_type"
                    ),
                    models.Index(
                        fields=["related_request"], name="idx_notifications_request_id"
                    ),
                    models.Index(
                        fields=["created_at"], name="idx_notifications_created_at"
                    ),
                ],
            },
        ),
    ]
