# Generated by Django 6.0.5 on 2026-05-29 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_add_client_name_email'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In Review'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='received', max_length=30)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='clients.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'requests',
                'indexes': [models.Index(fields=['tenant'], name='idx_requests_tenant_id'), models.Index(fields=['client'], name='idx_requests_client_id'), models.Index(fields=['provider'], name='idx_requests_provider_id'), models.Index(fields=['status'], name='idx_requests_status'), models.Index(fields=['tenant', 'status'], name='idx_requests_tenant_status'), models.Index(fields=['tenant', 'client', 'status'], name='idx_requests_tenant_client_status'), models.Index(fields=['is_deleted'], name='idx_requests_deleted'), models.Index(fields=['created_at'], name='idx_requests_created_at'), models.Index(fields=['due_date'], name='idx_requests_due_date'), models.Index(fields=['ai_category'], name='idx_requests_ai_category')],
            },
        ),
    ]
