# Generated by Django 6.0.5 on 2026-05-29 18:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0001_initial'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_source', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('ai', 'AI')], max_length=20)),
                ('event_type', models.CharField(choices=[('request_created', 'Request Created'), ('status_change', 'Status Change'), ('message_sent', 'Message Sent'), ('file_uploaded', 'File Uploaded'), ('note_added', 'Note Added'), ('delivery_created', 'Delivery Created'), ('ai_summary_generated', 'AI Summary Generated'), ('flag_toggled', 'Flag Toggled'), ('due_date_set', 'Due Date Set')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_activities',
            },
        ),
        migrations.RenameIndex(
            model_name='request',
            new_name='idx_requests_tcs',
            old_name='idx_requests_tenant_client_status',
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='request_management.request'),
        ),
        migrations.AddField(
            model_name='requestactivity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_activities', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['request'], name='idx_req_activities_request_id'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['tenant'], name='idx_req_activities_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['event_type'], name='idx_req_activities_event_type'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['request', 'created_at'], name='idx_req_activities_req_timeline'),
        ),
        migrations.AddIndex(
            model_name='requestactivity',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_req_activities_tenant_timeline'),
        ),
    ]
