# Generated by Django 6.0.5 on 2026-05-29 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0002_requestactivity_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internal_notes',
            },
        ),
        migrations.RenameIndex(
            model_name='requestactivity',
            new_name='idx_req_activities_req_tl',
            old_name='idx_req_activities_req_timeline',
        ),
        migrations.RenameIndex(
            model_name='requestactivity',
            new_name='idx_req_activities_tenant_tl',
            old_name='idx_req_activities_tenant_timeline',
        ),
        migrations.AddField(
            model_name='internalnote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='request_management.request'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='internalnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['request'], name='idx_internal_notes_request_id'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['tenant'], name='idx_internal_notes_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['user'], name='idx_internal_notes_user_id'),
        ),
        migrations.AddIndex(
            model_name='internalnote',
            index=models.Index(fields=['request', 'is_ai_generated'], name='idx_internal_notes_req_ai'),
        ),
    ]
