# Generated by Django 6.0.5 on 2026-05-29 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0003_internalnote_and_more'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('links', models.JSONField(blank=True, null=True)),
                ('delivery_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='request_management.request')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500)),
                ('file_url', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('file_extension', models.CharField(max_length=20)),
                ('is_delivery_file', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='request_management.delivery')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='request_management.request')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['request'], name='idx_deliveries_request_id'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['tenant'], name='idx_deliveries_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['created_by'], name='idx_deliveries_created_by_id'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['request', 'delivery_number'], name='idx_deliveries_req_number'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['tenant'], name='idx_files_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['request'], name='idx_files_request_id'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_by'], name='idx_files_uploaded_by_id'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['request', 'is_delivery_file'], name='idx_files_request_delivery'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_deleted'], name='idx_files_deleted'),
        ),
    ]
