# Generated by Django 6.0.5 on 2026-06-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0004_delivery_file_delivery_idx_deliveries_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='s3_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
