# Generated by Django 6.0.5 on 2026-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0005_file_s3_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
