# Generated by Django 6.0.5 on 2026-06-22 09:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_type", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.UUIDField()),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_actions",
                "indexes": [
                    models.Index(fields=["admin"], name="idx_admin_actions_admin_id"),
                    models.Index(
                        fields=["target_id"], name="idx_admin_actions_target_id"
                    ),
                    models.Index(fields=["action_type"], name="idx_admin_actions_type"),
                    models.Index(
                        fields=["created_at"], name="idx_admin_actions_created_at"
                    ),
                ],
            },
        ),
    ]
