# Generated by Django 6.0.5 on 2026-05-27 06:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_initial"),
        ("tenants", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientTagMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "client_tag_map",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("active", "Active")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status"], name="idx_clients_status"),
        ),
        migrations.AddField(
            model_name="clienttagmap",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tag_maps",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="tenants.tenant",
            ),
        ),
        migrations.AddField(
            model_name="clienttagmap",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_maps",
                to="clients.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(fields=["tenant", "name"], name="idx_tags_tenant_name"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("tenant", "name")},
        ),
        migrations.AddIndex(
            model_name="clienttagmap",
            index=models.Index(fields=["client"], name="idx_client_tag_map_client"),
        ),
        migrations.AddIndex(
            model_name="clienttagmap",
            index=models.Index(fields=["tag"], name="idx_client_tag_map_tag"),
        ),
        migrations.AlterUniqueTogether(
            name="clienttagmap",
            unique_together={("client", "tag")},
        ),
    ]
