# Generated by Django 6.0.5 on 2026-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_fix_nullable_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
