# Generated by Django 6.0.5 on 2026-06-02 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_add_client_name_email"),
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="membership",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to="tenants.tenantmembership",
            ),
        ),
    ]
