# Generated by Django 6.0.5 on 2026-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_tagline_accent_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(blank=True, default='#0F8536', max_length=7, null=True),
        ),
    ]
