# Generated by Django 6.0.5 on 2026-06-07 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_management', '0005_file_s3_key'),
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='request_management.request')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.tenant')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='request_management.file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
            ],
            options={
                'db_table': 'message_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['request'], name='idx_messages_request_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['tenant'], name='idx_messages_tenant_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='idx_messages_sender_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['request', 'created_at'], name='idx_messages_request_tl'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['request', 'is_read'], name='idx_messages_request_unread'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='idx_msg_attachments_message_id'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file'], name='idx_msg_attachments_file_id'),
        ),
    ]
